[package]
name = "flappy_bird"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15.1"
rand = "0.8.5"

[profile.release]
codegen-units = 1
lto = "thin"

[profile.wasm-release]
inherits = "release"
opt-level = "s"
strip = "debuginfo"